//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 01:38:14 PM EEST 
//


package com.parsing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.com.parsing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.com.parsing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link Users.User }
     * 
     */
    public Users.User createUsersUser() {
        return new Users.User();
    }

    /**
     * Create an instance of {@link Users.User.Roles }
     * 
     */
    public Users.User.Roles createUsersUserRoles() {
        return new Users.User.Roles();
    }

    /**
     * Create an instance of {@link Users.User.Roles.Role }
     * 
     */
    public Users.User.Roles.Role createUsersUserRolesRole() {
        return new Users.User.Roles.Role();
    }

}
